services:
  streamlit:
    container_name: streamlit-interface
    build: .
    entrypoint: ./entrypoint.sh
    ports:
      - "8501:8501"
    env_file:
      - .env
    environment:
      - DATABASE_URL=${DATABASE_URL:-postgresql://admin:admin@postgres:5432/vector_db}
    depends_on:
      - postgres

  postgres:
    image: pgvector/pgvector:pg17
    container_name: pgvector_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: vector_db
    ports:
      - "5432:5432"
    volumes:
      - pgvector_data:/var/lib/postgresql/data

volumes:
  pgvector_data:
